#-------------------------------
# General Site Settings
title: Elise A. Ralph
logo: logo.svg # You can add own logo.
description: Beautiful Tools


#-------------------------------
# Author Settings
author:
  name: Elise A. Ralph
  image: emmy.jpg
  say-hello: <strong>Elise</strong>
  bio: collecting, mining, analyzing, modeling, visualizing, and machine-learning data for over 35 years. 

#-------------------------------
# Contact links
twitter: https://twitter.com/ # Add your Twitter handle
facebook: https://facebook.com/ # Add your Facebook handle
dribbble: https://dribbble.com/ # Add your Dribbble handle
instagram: https://instagram.com/ # Add your Instagram handle
pinterest: https://pinterest.com/ # Add your Pinterest handle


#-------------------------------
# Instagram Feed
instafeed: # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: artemsheludko_ # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: 252797112# Add your identifier. For example UA-99631805-1.

#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
